SwedbankPay/swedbank-pay-design-guide-jekyll-theme

.github/workflows/jekyll.yml, README.md, _config.yml, payex.gemspec
Replace `PayEx` with `Swedbank Pay`.
=> Replace PayEx with Swedbank Pay

Gemfile, _config.yml, index.md
Currently supports a few emoji.
Why not all? I will investigate this.
=> Added crude emoji support

.github/workflows/jekyll.yml, .github/workflows/ruby.yml, Gemfile
Upgrade Faraday to 0.17.3 to fix the recent build problems. See github/personal-website#166 for details.
=> Upgrade Faraday to 0.17.3

_layouts/default.html
This sets the branch for edit to be develop, leading us to have less work when looking at pull requests.
=> Use develop for github edit branch

README.md
Restructure, fix links and add more details to readme
=> Restructure, fix links and add more details to readme

.github/workflows/build_and_deploy.yml
=> Add new github workflow

.github/workflows/build_and_deploy.yml
Sets the name to a more readable string, removes debug options since it does nothing.
=> Cleanup and rename

.github/workflows/build_and_deploy.yml
That way I don't have to hard code it in the action
=> Add gh_pages_publishing_source

_plugins/plant_uml.rb
My git config is weird as it won't allow me to ignore my fork as origin
=> Update plant uml to select less restrictive on casing

assets/css/swedbank-pay-design-guide-theme.scss, index.md
DX-889: Remove code styling on processed Mermaid diagrams.
=> DX-889: Remove code styling on processed Mermaid diagrams

.docker/docker-compose.ci.yml, docker-compose.yml
Tested localy with good results.
=> Update docker image to 1.3.3

.remarkrc.yaml, package-lock.json, package.json
Trying to fix the 
```
Could not find module `remark-squeeze-paragraphs`
```
message in Codacy
=> Remove remark-squeeze-paragraphs

_config.yml, index.md
Jekyll theme updated to use new Code View styling
=> Implement Code View

.github/workflows/deploy.yml, .remarkrc.yaml, CODE_OF_CONDUCT.md, LICENSE, README.md, docker-compose.yml, package-lock.json, package.json
Update license, badges and dependencies.
=> License, badges and dependencies

.github/workflows/pull-request.yml
Takes b1c78b496af0e64fb7aeae3e4914968301e8e94a from #150 for automatic pull request reviews from Dependabot.
=> Add automatic-pull-request-review GitHub Action

.rubocop.yml
Add RuboCop config file so Codacy can review our code according to sensible standards.
=> Add RuboCop config file

checkout-more/index.md, checkout/checkin.md, lib/sidebar.rb, lib/sidebar_html_builder.rb, lib/sidebar_page.rb, lib/sidebar_page_collection.rb, lib/sidebar_page_title.rb, lib/sidebar_parser.rb, lib/sidebar_renderer.rb, lib/sidebar_text_builder.rb, lib/sidebar_tree_builder.rb, spec/sidebar_checkin_file_spec.rb, spec/sidebar_checkout_more_file_spec.rb, spec/sidebar_front_page_spec.rb, spec/sidebar_spec.rb
Fix bugs introduced in #184 by reordering when stuff happens and refactoring the HTML parsing.
=> Yet more sidebar fixes

checkout/features/index.md, lib/sidebar_html_builder.rb, lib/sidebar_page_title.rb, lib/sidebar_text_builder.rb, spec/sidebar_features_file_spec.rb
DX-1263: Use the section title on non-leaf nodes
=> DX-1263: Use the section title on non-leaf nodes

.github/workflows/gem.yml
Bump GitVersion actions from `0.9.4` to `0.9.6` and GitVersion from `5.2.x` to `5.x.x`.
=> Bump GitVersion

_layouts/default.html, _sass/sidebar.scss
=> Add searchfield

_includes/accordion-table.html, _sass/accordion-table.scss, _sass/swedbank-pay-design-guide-theme.scss, checkout/checkin.md, index.md
Changed the design for property lists.
Property lists are inside an accordion
=> New property list design

_includes/apple-touch-startup-image.html, _layouts/default.html, spec/sidebar_after_payment_spec.rb, spec/sidebar_checkin_file_spec.rb, spec/sidebar_checkout_more_file_spec.rb, spec/sidebar_features_file_spec.rb, spec/sidebar_po_file_spec.rb
This fixes the titles used in the title header and `<title>` element.
=> Fix titles

_layouts/default.html, _layouts/search.html, search.md
Add back search form and content so the search starts working again.
=> DX-1288: Add back search form and content

_sass/front-page.scss
Added new color to links in front-page-hero
=> Link color frontpage

.github/workflows/test.yml, docker-compose.yml
=> Set site URL

_includes/google_analytics.html
[Anonymize IP addresses in Google Analytics](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization).
=> DX-1507: Anonymize IP addresses in Google Analytics

.github/workflows/deploy.yml, _config.yml
=> Rename master to main

.github/scripts/cherry-picker.sh, package-lock.json, package.json
Bump remark-lint packages in one go.
=> DX-1599: Bump remark-lint packages

swedbank-pay-design-guide-jekyll-theme.gemspec
Bump kramdown-plantuml from 1.1.9 to 1.1.10
=> DX-914: Bump kramdown-plantuml from 1.1.9 to 1.1.10

swedbank-pay-design-guide-jekyll-theme.gemspec
Bump kramdown-plantuml from 1.1.11 to 1.1.12
=> DX-914: Bump kramdown-plantuml from 1.1.11 to 1.1.12

_sass/swedbank-pay-design-guide-theme.scss, plantuml/index.md, swedbank-pay-design-guide-jekyll-theme.gemspec
Center-align PlantUML diagrams
=> DX-914: Center-align PlantUML diagrams

_includes/tabs.html, _sass/card.scss, checkout/v3/index.md
- Adds tabs functionality
- Aligns `card-extended` contents
=> Dx 1634 implemet tabs checkout v3

_includes/alert.html
Alerts looks wonky after an update in Design Guide. This will hopefully fix it.
=> DX-1719 Align alerts with Design Guide

.github/workflows/test.yml, .gitignore, .rubocop.yml, Gemfile, Rakefile, cards/index.md, checkout/v2/checkin.md, checkout/v2/index.md, checkout/v2/payment-menu.md, index.md, lib/sidebar_renderer.rb, spec/sidebar_spec.rb, spec/spec_helper.rb, spec/support/safe_strip.rb, spec/support/verifier.rb, spec/verifier_spec.rb, swedbank-pay-design-guide-jekyll-theme.gemspec
HTMLProofer and Rake should be development dependencies, not runtime dependencies.
=> HTMLProofer and Rake should be dev dependencies

_config.yml, lib/sidebar_html_builder.rb, spec/sidebar_features_file_spec.rb, spec/sidebar_index_file_spec.rb
Bringing Design Guide up to version 10.6.1 and tweeking sidebar to fit Sidebar v2
=> DX-2025 Update Design Guide version and added missing has-secondary-nav

_config.yml, _layouts/default.html, _sass/sidebar.scss, _sass/swedbank-pay-design-guide-theme.scss, assets/js/swedbank-pay-design-guide-theme.js
The HTML restructure aim to create a better user experience by rearranging the content. The content is now wrapping itself so the user does not need to use horizontal scrolling. The mobile view experience has improved due to the utility of the Topbar component from Design Guide combined with the Sidebar component.
=> Dx 2037 restructure html hierarchy

_sass/swedbank-pay-design-guide-theme.scss
=> DX-2055 Positioning search-box and elevate stack order

_layouts/default.html
Added two classed in default.html
=> DX-2218: Theme updates for moving of release notes and cards from front page

_layouts/front-page.html
Tried commenting out the default texts
=> DX-2219: Removing default texts from front page

_layouts/default.html, _layouts/front-page.html
Removed classes added to default.html
Removed default text for ingress and heading
=> dx-2221: Theme 2.1.10

_layouts/front-page.html
=> DX-2227: Final touches before WCAG demo
